print("1 - километры")
print("2 - метры")
print("3 - сантиметры")
print("4 - миллиметры")
print("5 - мили")
print("6 - ярды")

unit1 = int(input("Исходная единица: "))
unit2 = int(input("Целевая единица: "))
value = float(input("Введите расстояние: "))
